server:
    port: 8080

spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://ibooku.duckdns.org:3306/ibooku
        username: ${MARIADB_USERNAME}
        password: ${MARIADB_PASSWORD}

    jpa:
        open-in-view: false # Lazy loading을 사용하기 위해 Session을 Controller까지 유지하는 옵션
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true #To beautify or pretty print the SQL
                type:
                    preferred_uuid_jdbc_type: CHAR # UUID 타입을 CHAR 타입으로 매핑
                show_sql: true #show sql
        # 애플리케이션 실행 시점에서 데이터베이스 연결이 아직 준비되지 않았더라도 예외가 발생 안함. 어플리케이션 안전성과 신뢰성 높임
        defer-datasource-initialization: true
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    sql:
        init:
            mode: always

    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MARIADB_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    timeout: 5000
                    starttls:
                        enable: true

logging:
    log4j2:
        config: log4j2.yml